#!/bin/bash

repo_42="/home/yioffe/Projects/School-42"
current_date=$(date +"%d-%m-%Y")
location="school"

if [ -z "$1" ]; then
    repo_path=$(pwd)
elif [[ "$1" == "42" ]]; then
    repo_path="$repo_42"
else
    echo "wrong push parameter"
    exit 1
fi

cd "$repo_path" || exit
git add .

if [[ -n "$2" ]]; then
	commit_message="$2"
else
	commit_message="$location $current_date"
fi

git commit -m "$commit_message"
git push
